

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties # configmap name
# key-value pair configMap
data:
  appUrl: "http://app-url"
  timeout: "30"

# `kubectl apply -f 01-....`
# get configMap: `kubectl get configmap` || `kubectl get cm`
# get details: `kubectl describe cm <configmap_name>` -> `kubectl describe cm app-properties`
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    # inject configMap as env variables
    env:
    - name: "request.timeout"
      # get value from configMap
      valueFrom:
        configMapKeyRef:
          name: app-properties
          key: timeout
    - name: "application.url"
      valueFrom:
        configMapKeyRef:
          name: app-properties
          key: appUrl
    # print env variables when pod start
    args:
    - env          

# run: `kubectl apply -f 01-...`

# check log: `kubectl logs my-pod`: request.timeout & application.url info were printed out